cuda-11.8 loaded successful
gcc-9.3.0 loaded successful

EnvironmentNameNotFound: Could not find conda environment: LMMSeg_cp310
You can list all discoverable environments with `conda info --envs`.


Traceback (most recent call last):
  File "/home/bingxing2/home/scx8ah2/jiaxin/DeformVOS/methods/CFBI/tools/eval_net.py", line 4, in <module>
    from networks.engine.eval_manager import Evaluator
  File "/home/bingxing2/home/scx8ah2/jiaxin/DeformVOS/methods/CFBI/./networks/engine/eval_manager.py", line 5, in <module>
    import torch
  File "/home/bingxing2/apps/anaconda/2021.11/lib/python3.9/site-packages/torch/__init__.py", line 228, in <module>
    _load_global_deps()
  File "/home/bingxing2/apps/anaconda/2021.11/lib/python3.9/site-packages/torch/__init__.py", line 187, in _load_global_deps
    raise err
  File "/home/bingxing2/apps/anaconda/2021.11/lib/python3.9/site-packages/torch/__init__.py", line 168, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/bingxing2/apps/anaconda/2021.11/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/bingxing2/apps/anaconda/2021.11/lib/python3.9/site-packages/torch/lib/libtorch_global_deps.so: cannot open shared object file: No such file or directory
