cuda-11.8 loaded successful
gcc-9.3.0 loaded successful
Could not find the bitsandbytes CUDA binary at PosixPath('/home/bingxing2/home/scx8ah2/.conda/envs/LLMSeg_cp310/lib/python3.10/site-packages/bitsandbytes-0.43.2.dev0-py3.10-linux-aarch64.egg/bitsandbytes/libbitsandbytes_cuda118.so')
Could not load bitsandbytes native library: /home/bingxing2/home/scx8ah2/.conda/envs/LLMSeg_cp310/lib/python3.10/site-packages/bitsandbytes-0.43.2.dev0-py3.10-linux-aarch64.egg/bitsandbytes/libbitsandbytes_cpu.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/bingxing2/home/scx8ah2/.conda/envs/LLMSeg_cp310/lib/python3.10/site-packages/bitsandbytes-0.43.2.dev0-py3.10-linux-aarch64.egg/bitsandbytes/cextension.py", line 109, in <module>
    lib = get_native_library()
  File "/home/bingxing2/home/scx8ah2/.conda/envs/LLMSeg_cp310/lib/python3.10/site-packages/bitsandbytes-0.43.2.dev0-py3.10-linux-aarch64.egg/bitsandbytes/cextension.py", line 96, in get_native_library
    dll = ct.cdll.LoadLibrary(str(binary_path))
  File "/home/bingxing2/home/scx8ah2/.conda/envs/LLMSeg_cp310/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/home/bingxing2/home/scx8ah2/.conda/envs/LLMSeg_cp310/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/bingxing2/home/scx8ah2/.conda/envs/LLMSeg_cp310/lib/python3.10/site-packages/bitsandbytes-0.43.2.dev0-py3.10-linux-aarch64.egg/bitsandbytes/libbitsandbytes_cpu.so: cannot open shared object file: No such file or directory

CUDA Setup failed despite CUDA being available. Please run the following command to get more information:

python -m bitsandbytes

Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

[2024-07-24 20:41:52,564] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
